services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    env_file:
      - path: .env.shared
      - path: .env.${ENV} # ENV = dev or prod
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=phi3:3.8b
    depends_on:
      - ollama
    command: ${LAUNCH_CMD}

  ollama:
    image: ollama/ollama:0.12.4
