services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=qwen:0.5b
    stdin_open: true
    tty: true
    depends_on:
      - ollama
    command: pnpm dev

  ollama:
    build: ./docker/ollama/
    ports:
      - "11434:11434"
