services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    env_file:
      - path: .env.shared
      - path: .env.${ENV} # ENV = dev or prod
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - AI_VOICE_HOST=http://kokoro:8880
    depends_on:
      - ollama
      - kokoro
    command: ${LAUNCH_CMD}

  ollama:
    restart: unless-stopped
    build:
      dockerfile: ./docker/ollama/Dockerfile

  kokoro:
    restart: unless-stopped
    image: ghcr.io/remsky/kokoro-fastapi-cpu
    ports:
      - 8880:8880
