services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=phi3:3.8b
    stdin_open: true
    tty: true
    depends_on:
      - ollama
    command: pnpm dev

  ollama:
    image: ollama/ollama:0.12.4
